apiVersion: v1
kind: Secret
metadata:
  name: polaris-persistence-secret
  namespace: polaris
type: Opaque
stringData:
  username: "polaris"
  password: "polaris"
  jdbcUrl: "jdbc:postgresql://polaris-postgresql.polaris.svc.cluster.local:5432/polaris"
